apiVersion: v1
kind: Service
metadata:
  name: hunter-service
spec:
  selector:
    app: hunter
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
      #nodePort: 30007 # This line is not needed for LoadBalancer and can be removed

